version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: barostart-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: barostart
      TZ: Asia/Seoul
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - barostart-mysql-data:/var/lib/mysql

volumes:
  barostart-mysql-data:
