spring:
  application:
    name: BaroStart-BE
  datasource:
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: false
    open-in-view: false

#oci:
#  tenant-id: ${OCI_TENANT_ID}
#  user-id: ${OCI_USER_ID}
#  fingerprint: ${OCI_FINGERPRINT}
#  private-key-path: ${OCI_PRIVATE_KEY_PATH}
#  region: ${OCI_REGION}
#  bucket:
#    name: ${OCI_BUCKET_NAME}
#    namespace: ${OCI_BUCKET_NAMESPACE}
