spring:
  application:
    name: BaroStart-BE

  datasource:
    username: ${DATABASE_USERNAME}
    url: ${DATABASE_URL}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      ssl:
        enabled: ${SSL_ENABLED:true}

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    show_sql: false
    open-in-view: false

jwt:
  secret: { JWT_SECRET }
  issuer: { JWT_ISSUER }
  token:
    expire: { JWT_TOKEN_EXPIRE }
  refresh:
    expire: { JWT_REFRESH_EXPIRE }

oci:
  tenant-id: ${OCI_TENANT_ID}
  user-id: ${OCI_USER_ID}
  fingerprint: ${OCI_FINGERPRINT}
  private-key-path: ${OCI_PRIVATE_KEY_PATH}
  region: ${OCI_REGION}
  bucket:
    name: ${OCI_BUCKET_NAME}
    namespace: ${OCI_BUCKET_NAMESPACE}

app:
  server:
    url: ${APP_SERVER_URL}
  service:
    url: ${APP_SERVICE_URL}
